// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkpwhzhbrxbhxypyslmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrcHdoemhicnhiaHh5cHlzbG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODY3OTAsImV4cCI6MjA2ODk2Mjc5MH0.EI56NHQmAycKNbLy_40X9PGGT-VZtI75yDcoV4bpq70";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});